export default {
    FETCH_COMPANIES_REQUEST: '@@companies/FETCH_COMPANIES_REQUEST',
    FETCH_COMPANIES_SUCCESS: '@@companies/FETCH_COMPANIES_SUCCESS',
    FETCH_COMPANIES_ERROR: '@@companies/FETCH_COMPANIES_ERROR',
};
